name: ci

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create image from repository
        run: docker build -t ghcr.io/${{ github.actor }}/shuff_box .

      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.actor }}/shuff_box:latest